name: Build BedwarsClient

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Setup Decomp Workspace
      run: ./gradlew setupDecompWorkspace --no-daemon --stacktrace
      continue-on-error: true
    
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --stacktrace
    
    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BedwarsClient
        path: build/libs/*.jar
        if-no-files-found: warn
